version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/authdb
      - JWT_SECRET=your_jwt_secret
      - PORT=5000
    depends_on:
      - mongo

volumes:
  mongo_data: